Oxind\FeedbackBundle\Entity\FeedbackType:
    type: mappedSuperclass
    table: feedback_type
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 45
            unique: true
        statuses:
            type: array
        votable:
            type: boolean
        vote_min_point:
            type: integer
        vote_max_point:
            type: integer
        displayable_statuses:
            type: array
        timeline_start_status:
            type: string
        timeline_end_status:
            type: string
        credit_vote_status:
            type: string