Oxind\FeedbackBundle\Entity\Feedback:
    type: mappedSuperclass
    table: feedback
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: string
            length: 2000
        status:
            type: string
            length: 45
        created_at:
            type: datetime
        updated_at:
            type: datetime
        deleted_at:
            type: datetime
            nullable: true
