Oxind\FeedbackBundle\Entity\FeedbackDisplay:
    type: mappedSuperclass
    table: feedback_display
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        start_date:
            type: datetime
        end_date:
            type: datetime
            nullable: true