Oxind\FeedbackBundle\Entity\Vote:
    type: mappedSuperclass
    table: vote
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        points:
            type: integer
#    manyToOne:
#        feedback:
#            targetEntity: Feedback
#            inversedBy: votes
#            joinColumn:
#                name: feedback_id
#                referencedColumnName: id
#                nullable: false