parameters:
#    oxind_feedback.example.class: Oxind\FeedbackBundle\Example

services:
#    oxind_feedback.example:
#        class: %oxind_feedback.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
